name: Upload a Docker image to AWS ECR

on:
  push:
    branches:
      - nick-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build Docker Image
        run: docker build -t frontend-image .
        working-directory: ./docker

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true # Protect your password
          registry-type: private
          skip-logout: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1 # Region is now explicitly set

      - name: Tag Docker Image
        run: docker tag frontend-image ${{ steps.login-ecr.outputs.registry }}:v0.1

      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}:v0.1
