name: Upload a Docker image to AWS ECR

on:
  push:
    branches:
      - nick-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build Docker Image
        run: docker build -t frontend-image .
        working-directory: ./docker

      - name: Authenticate to ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/o3i0k7i9

      - name: Tag Docker Image
        run: docker tag frontend-image public.ecr.aws/o3i0k7i9/my-ecr-repo:latest # Replace with your actual repository name

      - name: Push Docker Image to ECR
        run: docker push public.ecr.aws/o3i0k7i9/my-ecr-repo:latest # Replace with your actual repository name


      # Removed the redundant Amazon ECR Login step
